### ISSUE TITLE
Add ingress whitelist to EKS hosted installer

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-self-hosted-installers#106]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

**Comment by rshade** [comment]
## Analysis & Implementation Plan

After analyzing the EKS hosted installer architecture, I've identified the scope and requirements for adding ingress whitelist functionality to restrict access to the Pulumi Service. Here's a systematic breakdown:

### Current State Analysis ✅

**Current Architecture:**
- EKS uses AWS Application Load Balancer (ALB) with Kubernetes ingress controller
- Security group created in `10-cluster-svcs` stack via `createAlbSecurityGroup()` function  
- ALB security group currently allows **all internet traffic** (`0.0.0.0/0`) on ports 80 and 443
- API and Console ingress resources reference this security group via `config.albSecurityGroupId`

**Security Risk:**
- Pulumi Service is publicly accessible from any IP address
- No IP-based access control at the load balancer level

### Implementation Plan

#### Phase 1: Core Security Enhancement (High Priority)
- [ ] **Design configuration schema for ingress IP whitelist**
  - Define CIDR block array configuration parameter
  - Support multiple IP ranges and individual IPs
  - Provide clear configuration examples

- [ ] **Add ingress whitelist configuration to 10-cluster-svcs config.ts**
  - Add `ingressAllowedCidrs` parameter with default fallback
  - Read from Pulumi configuration with sensible defaults
  - Support both environment-specific and common CIDR lists

- [ ] **Modify createAlbSecurityGroup function to accept CIDR whitelist**
  - Update `AlbSecGroupOptions` interface to include CIDR array
  - Pass whitelist configuration from main stack to security group creation
  - Maintain clean separation of concerns

- [ ] **Update HTTP/HTTPS security group rules to use whitelist CIDRs**
  - Replace `cidrBlocks: ["0.0.0.0/0"]` with configurable CIDR array
  - Apply same whitelist to both HTTP (port 80) and HTTPS (port 443) rules
  - Ensure proper security group rule naming and descriptions

#### Phase 2: Robustness & Usability (Medium Priority)
- [ ] **Add validation for CIDR block format and ranges**
  - Validate CIDR notation (e.g., "192.168.1.0/24", "10.0.0.1/32")
  - Prevent invalid or potentially dangerous configurations
  - Provide helpful error messages for misconfigurations

- [ ] **Update Pulumi.README.yaml with ingress whitelist examples**
  - Add example CIDR configurations for common scenarios
  - Document corporate network, VPN, and specific IP examples
  - Include security best practices and recommendations

- [ ] **Ensure backward compatibility with existing deployments**
  - Default to current behavior (0.0.0.0/0) if no whitelist specified
  - Provide migration path for existing installations
  - Clear upgrade documentation for security hardening

#### Phase 3: Testing & Documentation (Medium-Low Priority)
- [ ] **Create tests to verify whitelist functionality**
  - Unit tests for CIDR validation and security group rule generation
  - Integration tests to verify ALB behavior with restricted access
  - Test scenarios for various CIDR configurations

- [ ] **Update EKS README with whitelist configuration documentation**
  - Security section explaining ingress access control
  - Step-by-step configuration instructions
  - Troubleshooting guide for access issues

### Technical Implementation Details

**Security Group Rule Modification:**
```typescript
// Current (allows all):
cidrBlocks: [ "0.0.0.0/0" ]

// Enhanced (whitelist-based):
cidrBlocks: args.ingressAllowedCidrs || [ "0.0.0.0/0" ]
```

**Configuration Schema:**
```yaml
# Example Pulumi.yaml configuration
config:
  # Restrict access to corporate network and specific IPs
  ingressAllowedCidrs:
    - "10.0.0.0/8"      # Corporate network
    - "203.0.113.1/32"  # Specific admin IP
    - "198.51.100.0/24" # Remote office network
```

**Security Benefits:**
- **Reduced attack surface**: Only whitelisted IPs can reach Pulumi Service
- **Compliance**: Meets enterprise security requirements for infrastructure access
- **Defense in depth**: Additional security layer beyond application-level authentication
- **Network-level blocking**: Invalid requests stopped at load balancer, reducing server load

### Success Criteria
1. ✅ ALB security group rules use configurable CIDR whitelist instead of 0.0.0.0/0
2. ✅ Backward compatibility maintained for existing deployments  
3. ✅ Clear configuration examples and documentation provided
4. ✅ Input validation prevents misconfigurations
5. ✅ Security enhancement is opt-in with sensible defaults

This implementation will provide enterprise-grade network access control for the EKS-hosted Pulumi Service while maintaining ease of use and backward compatibility.

🤖 Generated analysis with Claude Code
