### ISSUE TITLE
[EPIC] - Insights support in self-hosted

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-self-hosted-installers#156]
With self-hosted support for [Insights](https://www.pulumi.com/docs/pulumi-cloud/insights/) available, the self-hosted installers need to be updated to include this new functionality.

```[tasklist]
### Tasks
- [x] AWS EKS Installer
- [x] AWS ECS Installer - GO
- [x] Azure AKS Installer
- [x] GCP GKE Installer
- [x] BYO Installer
```

**Comment by phillipedwards** [comment]
Reference opensearch implementation in the all-in-one docker compose
- docs
- update code to include new infra.

**Comment by phillipedwards** [comment]
Things to consider (not exhaustive):
- the infrastructure to create the opensearch cluster (could be AWS managed or container based)
- Pulumi API needs the opensearch domain, username, and password to communicate with the cluster's endpoint
- if our Pulumi program is creating the opensearch cluster we will need a mechanism to support SSL between the API and the cluster
- For BYO infra example, we should expect to consumer (customer) to provide their own opensearch cluster.

**Comment by phillipedwards** [comment]
Insights has made its way into pulumi self-hosted docker images:
- https://hub.docker.com/r/pulumi/service
- https://hub.docker.com/r/pulumi/console
- - https://hub.docker.com/r/pulumi/migrations
