### ISSUE TITLE
Add Certificate Manager to the self-hosted component microstacks.

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi-self-hosted-installers#171]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
We need to use certificate manager to issue certificates so that open search will work across namespaces.

**Comment by rshade** [comment]
## Analysis & Implementation Plan

After analyzing the current codebase, I've identified the scope and requirements for adding Certificate Manager support to enable OpenSearch cross-namespace functionality. Here's a systematic breakdown:

### Current State Analysis ✅

**What exists:**
- `components-microstacks/cert-manager.ts` - Azure-specific cert-manager component
- AKS deployment uses cert-manager in stages 02-kubernetes and 03-application
- OpenSearch components exist in `components-microstacks/openSearch.ts`

**What's missing:**
- EKS, GKE, and ECS deployments lack cert-manager integration
- Current cert-manager only supports Azure DNS challenges (not AWS Route53, Google Cloud DNS)
- OpenSearch lacks TLS configuration for secure cross-namespace communication
- No certificate provisioning for OpenSearch service-to-service communication

### Implementation Plan

#### Phase 1: Core Infrastructure (High Priority)
- [ ] **Research OpenSearch cross-namespace certificate requirements**
  - Document specific TLS needs for OpenSearch cluster communication
  - Identify certificate types needed (CA, server, client certs)
  - Define namespace security model

- [ ] **Design generic cert-manager component supporting AWS, Azure, GCP**
  - Create cloud-agnostic interface for DNS challenges
  - Support AWS Route53, Azure DNS, Google Cloud DNS
  - Maintain backward compatibility with existing AKS usage

- [ ] **Refactor existing Azure-specific cert-manager to be cloud-agnostic**
  - Extract Azure-specific logic into provider-specific modules
  - Create common interface for certificate issuance
  - Update components-microstacks/cert-manager.ts

- [ ] **Update OpenSearch component to support TLS certificates**
  - Add certificate configuration to OpenSearch Helm values
  - Configure inter-node and client-server TLS
  - Enable certificate-based authentication

#### Phase 2: Platform Integration (Medium Priority)
- [ ] **Integrate cert-manager into EKS deployment**
  - Add cert-manager installation to EKS cluster services
  - Configure Route53 DNS challenges
  - Update OpenSearch deployment in 90-pulumi-service

- [ ] **Integrate cert-manager into GKE deployment**
  - Add cert-manager to 02-kubernetes stage
  - Configure Google Cloud DNS challenges
  - Update OpenSearch in 03-application stage

#### Phase 3: Completion (Medium-Low Priority)
- [ ] **Integrate cert-manager into ECS deployment (if applicable)**
  - Evaluate if cert-manager is needed for ECS-based OpenSearch
  - Implement if OpenSearch runs in ECS containers

- [ ] **Update platform documentation for cert-manager integration**
  - Update README files for affected platforms
  - Add certificate configuration examples
  - Document troubleshooting steps

- [ ] **Add tests for cross-namespace OpenSearch certificate validation**
  - Create integration tests for certificate provisioning
  - Test cross-namespace OpenSearch communication
  - Validate certificate rotation scenarios

### Technical Considerations

**Certificate Requirements:**
- Cluster-level certificates for OpenSearch inter-node communication
- Service certificates for API endpoints
- Client certificates for secure authentication
- Support for certificate rotation and renewal

**Multi-Cloud Support:**
- AWS: Route53 DNS challenges, IAM role authentication
- Azure: Azure DNS challenges, Managed Identity authentication  
- GCP: Google Cloud DNS challenges, Workload Identity authentication

**Security:**
- Follow principle of least privilege for DNS challenge permissions
- Secure certificate storage in Kubernetes secrets
- Enable automatic certificate renewal

### Success Criteria
1. OpenSearch clusters can communicate securely across namespaces
2. All supported platforms (EKS, AKS, GKE) have cert-manager integration
3. Certificate provisioning is automated and cloud-agnostic
4. Documentation clearly explains certificate configuration
5. Tests validate cross-namespace functionality

This implementation will enable secure OpenSearch deployments across all supported cloud platforms with proper certificate management.

🤖 Generated analysis with Claude Code

**Comment by rshade** [comment]
@claude:
1. Typo in OpenSearch Interface - components-microstacks/openSearch.ts:23
intitialAdminPassword: Input<string>;  // Should be "initialAdminPassword"
Impact: Propagates to all platform implementations. Consider fixing in a follow-up PR to avoid breaking existing configurations.

2. cert-manager Version Pinning - components-microstacks/cert-manager.ts:83
version: "1.12.1",  // Consider updating to latest stable (1.16.x)
Recommendation: The current version is from mid-2023. While functional, newer versions have security improvements and bug fixes.

3. ClusterIssuer Metadata Issue - components-microstacks/cert-manager.ts:381
metadata: {
    namespace: args.namespaceName  // ClusterIssuer is cluster-scoped - should not have namespace
}
Impact: This could cause deployment issues as ClusterIssuer resources are cluster-scoped.
